use std::collections::BTreeSet;

use anyhow::{Context, Result, bail};
use serde::Deserialize;

#[derive(Deserialize)]
struct Snapshot {
    rules: Vec<DocRule>,
}

#[derive(Deserialize)]
struct DocRule {
    id: String,
    #[serde(default = "default_confidence")]
    confidence: String,
    #[serde(default = "default_true")]
    visible: bool,
    validation: Option<serde_yaml::Value>,
    revocation: Option<serde_yaml::Value>,
}

pub fn generate_builtin_rules_page(snapshots: &[&str]) -> Result<String> {
    let mut rules = Vec::new();
    for (source, yaml) in snapshots.iter().enumerate() {
        let yaml = &**yaml;
        let snapshot: Snapshot = serde_yaml::from_str(yaml).with_context(|| {
            format!("failed to read generated rule source #{source} for documentation")
        })?;
        rules.extend(snapshot.rules);
    }
    rules.sort_by(|left, right| left.id.cmp(&right.id));

    let mut ids = BTreeSet::new();
    for rule in &rules {
        if !ids.insert(rule.id.as_str()) {
            bail!("duplicate built-in rule ID {} while generating documentation", rule.id);
        }
    }

    let validation_count = rules.iter().filter(|rule| rule.validation.is_some()).count();
    let revocation_count = rules.iter().filter(|rule| rule.revocation.is_some()).count();
    let helper_count = rules.iter().filter(|rule| !rule.visible).count();

    let mut page = format!(
        r#"---
title: "Built-in Rules"
description: "Generated list of Kingfisher's {rule_count} built-in Betterleaks and Veles rules, including validation and revocation support."
---

# Built-in Rules

<!-- Generated by crates/kingfisher-rules/build.rs. Do not edit manually. -->

Kingfisher embeds **{rule_count} rules** from the Betterleaks and Veles sources. Of these,
**{validation_count}** include validation and **{revocation_count}** support direct revocation.
The catalog includes **{helper_count} hidden component/helper rules** used to assemble composite
credentials.

`Yes` means the operation is embedded in the current build. `None` means the rule detects findings
but does not provide that operation.

!!! tip "Search"
    Filter by rule ID, confidence, validation, or revocation support.

<input type="text" class="rules-search" placeholder="Search rules... (e.g. github, HTTP, revocation)" />
<div class="rules-count"></div>

<table class="rules-table">
<thead>
<tr>
<th>Rule ID</th>
<th>Confidence</th>
<th>Validation</th>
<th>Revocation</th>
</tr>
</thead>
<tbody>
"#,
        rule_count = rules.len(),
    );

    for rule in rules {
        page.push_str(&format!(
            "<tr>\n<td><code>{}</code></td>\n<td>{}</td>\n<td>{}</td>\n<td>{}</td>\n</tr>\n",
            escape_html(&rule.id),
            title_case(&rule.confidence),
            support_label(rule.validation.is_some()),
            support_label(rule.revocation.is_some()),
        ));
    }
    page.push_str("</tbody>\n</table>\n");
    Ok(page)
}

fn support_label(supported: bool) -> &'static str {
    if supported { "Yes" } else { "None" }
}

fn escape_html(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

fn title_case(value: &str) -> String {
    let mut chars = value.chars();
    chars
        .next()
        .map_or_else(String::new, |first| first.to_uppercase().collect::<String>() + chars.as_str())
}

fn default_confidence() -> String {
    "medium".to_string()
}

fn default_true() -> bool {
    true
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn documents_combined_capability_types() {
        let page = generate_builtin_rules_page(&[
            r#"
rules:
  - name: Expression token
    id: betterleaks.expression-token
    pattern: token
    confidence: high
    validation:
      type: Betterleaks
      content: {}
    revocation:
      type: HttpMultiStep
      content: { steps: [] }
"#,
            r#"
rules:
  - name: Raw token
    id: veles.secrets/raw
    pattern: token
    visible: false
    validation:
      type: Raw
      content: gcs_hmac
"#,
        ])
        .unwrap();

        assert!(page.contains("**2 rules**"));
        assert!(page.contains("**2** include validation"));
        assert!(page.contains("**1** support direct revocation"));
        assert!(!page.contains("<th>Rule Name</th>"));
        assert!(!page.contains("<th>Catalog</th>"));
        assert!(!page.contains("Expression token"));
        assert!(page.contains("Yes</td>"));
        assert!(page.contains("None</td>"));
        assert!(!page.contains("Raw token"));
    }

    #[test]
    fn labels_all_capability_types_as_yes() {
        let page = generate_builtin_rules_page(&[r#"
rules:
  - { name: JWT, id: betterleaks.jwt, pattern: token, validation: { type: JWT } }
  - { name: HTTP, id: betterleaks.http, pattern: token, validation: { type: Http, content: {} }, revocation: { type: AWS } }
"#])
        .unwrap();

        assert_eq!(page.matches("Yes</td>").count(), 3);
    }

    #[test]
    fn escapes_untrusted_upstream_metadata() {
        let page = generate_builtin_rules_page(&[r#"
rules:
  - name: <script>alert('x')</script>
    id: veles.<script>alert('x')</script>
    pattern: token
"#])
        .unwrap();

        assert!(!page.contains("<script>"));
        assert!(page.contains("veles.&lt;script&gt;alert(&#39;x&#39;)&lt;/script&gt;"));
    }
}
