from os import PathLike
from pathlib import Path
from typing import Any, Mapping, Iterator
from .scanner import DetectionPolicy

__version__: str

def shannon_entropy(data: bytes) -> float: ...

class Rules:
    def __init__(self, paths: list[str], builtins: bool, confidence: str, *,
                 cache: bool = True, cache_dir: str | None = None) -> None: ...
    def metadata(self) -> list[dict[str, Any]]: ...
    def detail(self, rule_id: str) -> dict[str, Any]: ...
    def __len__(self) -> int: ...
    @property
    def cache_status(self) -> str: ...

class CancellationToken:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    @property
    def is_cancelled(self) -> bool: ...

class Finding:
    @property
    def visible(self) -> bool: ...
    @property
    def rule_id(self) -> str: ...
    @property
    def secret(self) -> str: ...
    @property
    def rule_name(self) -> str: ...
    @property
    def entropy(self) -> float: ...
    @property
    def fingerprint(self) -> int: ...
    @property
    def blob_id(self) -> str: ...
    @property
    def is_base64_encoded(self) -> bool: ...
    @property
    def confidence(self) -> str: ...
    @property
    def location(self) -> dict[str, int]: ...
    @property
    def captures(self) -> dict[str, str]: ...
    def to_dict(self, redact: bool) -> dict[str, Any]: ...

class Scanner:
    def __init__(self, rules: Rules, base64: bool, dedup: bool, redact: bool,
                 min_entropy: float | None, *, policy: DetectionPolicy | None = None) -> None: ...
    def scan_bytes(self, data: bytes, *, timeout: float | None = None,
                   cancellation: CancellationToken | None = None) -> list[Finding]: ...
    def scan_file(self, path: str, *, timeout: float | None = None,
                  cancellation: CancellationToken | None = None) -> list[Finding]: ...
    def scan_input(self, data: bytes, path: str, *, timeout: float | None = None,
                   cancellation: CancellationToken | None = None) -> list[Finding]: ...
    def reset_dedup(self) -> None: ...

class Validator:
    def __init__(self, timeout: float, concurrency: int, retries: int,
                 max_response_bytes: int, allow_internal_ips: bool,
                 variables: Mapping[str, str]) -> None: ...
    def validate(self, findings: list[Finding], *, timeout: float | None = None,
                 cancellation: CancellationToken | None = None) -> list[dict[str, Any]]: ...

class Revoker:
    def __init__(self, rules: Rules, timeout: float) -> None: ...
    def revoke(self, rule_id: str, secret: str, variables: Mapping[str, str], *,
               timeout: float | None = None,
               cancellation: CancellationToken | None = None) -> dict[str, Any]: ...

class Filesystem(Iterator[Path]):
    def __init__(self, roots: list[str], *, gitignore: bool = True, hidden: bool = False,
                 max_file_size: int | None = None, timeout: float | None = None,
                 cancellation: CancellationToken | None = None) -> None: ...
    def __iter__(self) -> Filesystem: ...
    def __next__(self) -> Path: ...


class GitCommit:
    @property
    def id(self) -> str: ...
    @property
    def author(self) -> tuple[str, str, int, int]: ...
    @property
    def committer(self) -> tuple[str, str, int, int]: ...
    @property
    def parents(self) -> list[str]: ...
    @property
    def message(self) -> str: ...

class GitInputs(Iterator[tuple[str, bytes | None, str, list[GitCommit], bool, bool | None, bytes, str | None]]):
    def __init__(self, path: str | PathLike[str], scope: object, *,
                 timeout: float | None = None, cancellation: CancellationToken | None = None,
                 discover: bool = True, max_blob_size: int | None = None,
                 max_commits: int | None = None, max_inputs: int | None = None,
                 skip_missing_blobs: bool = False) -> None: ...
    def __iter__(self) -> GitInputs: ...
    def __next__(self) -> tuple[str, bytes | None, str, list[GitCommit], bool, bool | None, bytes, str | None]: ...

def expand_archive(path: str, data: bytes | None, *, file: str | None = None,
                   depth: int = 1, max_bytes: int = 268435456, max_entries: int = 10000,
                   timeout: float | None = None,
                   cancellation: CancellationToken | None = None,
                   temp_dir: str | PathLike[str] | None = None) -> list[tuple[str, bytes]]: ...

def expand_content(path: str, data: bytes | None, *, file: str | PathLike[str] | None = None,
                   sqlite: bool = True, pyc: bool = True, strict: bool = False,
                   max_bytes: int = 268435456, timeout: float | None = None,
                   cancellation: CancellationToken | None = None,
                   temp_dir: str | PathLike[str] | None = None) -> tuple[list[tuple[str, bytes]] | None, str | None]: ...
