from typing import Mapping

__version__: str

def shannon_entropy(data: bytes) -> float: ...

class Rules:
    def __init__(self, paths: list[str], builtins: bool, confidence: str) -> None: ...
    def metadata(self) -> str: ...
    def detail(self, rule_id: str) -> str: ...

class CancellationToken:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    @property
    def is_cancelled(self) -> bool: ...

class Finding:
    @property
    def visible(self) -> bool: ...
    def to_json(self, redact: bool) -> str: ...

class Scanner:
    def __init__(self, rules: Rules, base64: bool, dedup: bool, redact: bool,
                 min_entropy: float | None) -> None: ...
    def scan_bytes(self, data: bytes, *, timeout: float | None = None,
                   cancellation: CancellationToken | None = None) -> list[Finding]: ...
    def scan_file(self, path: str, *, timeout: float | None = None,
                  cancellation: CancellationToken | None = None) -> list[Finding]: ...
    def reset_dedup(self) -> None: ...

class Validator:
    def __init__(self, timeout: float, concurrency: int, retries: int,
                 max_response_bytes: int, allow_internal_ips: bool,
                 variables: Mapping[str, str]) -> None: ...
    def validate(self, findings: list[Finding]) -> str: ...

class Revoker:
    def __init__(self, rules: Rules, timeout: float) -> None: ...
    def revoke(self, rule_id: str, secret: str, variables: Mapping[str, str]) -> str: ...
