name: CI Pull Request

on:
   pull_request:
     branches:
       - main

# This workflow runs on pull requests to the main branch
# It builds the project for 2 platforms, Linux arm64 and macOS arm64,
# and runs tests for each platform. All platforms tested on merge to main
jobs:
   linux-arm64:
     name: Linux arm64
     runs-on: ubuntu-24.04-arm
     steps:
       - uses: actions/checkout@v4
       - uses: actions-rs/toolchain@v1
         with:
           toolchain: 1.85.0
           profile: minimal
           override: true
       - uses: swatinem/rust-cache@v2
       - name: Build (Makefile linux-arm64)
         run: make ubuntu-arm64
       - name: Run tests
         run: make tests

   macos-arm64:
     name: macOS arm64
     runs-on: macos-14
     steps:
       - uses: actions/checkout@v4
       - uses: actions-rs/toolchain@v1
         with:
           toolchain: 1.85.0
           profile: minimal
           override: true
       - uses: swatinem/rust-cache@v2
       - name: Build (Makefile darwin-arm64)
         run: make darwin-arm64
       - name: Run tests
         run: make tests
